#!/usr/bin/env python3
from __future__ import annotations

from typing import Any, Dict, List


def build_stage_tx_meta_doc(
    *,
    session_id: str,
    loop_idx: int,
    stage: str,
    started_utc: str,
    ended_utc: str,
    ok: bool,
    rc: int,
    err: str,
    contract_errors: List[str],
    attempt_records: List[Dict[str, Any]],
    stage_spec_errors: List[str],
    failure_category: str,
    failure_recoverable: bool,
    failure_context: Dict[str, Any],
    before_snapshot: str,
    after_snapshot: str,
    log_rel: str,
    is_exploit_stage: bool,
    exp_verify_ok: Any,
    exp_verify_report: str,
    exp_autofix_attempts: int,
    exp_autofix_last_error: str,
    stage_cache_hit: bool,
    stage_cache_ref: str,
    stage_cache_saved: str,
    bundled: bool,
) -> Dict[str, Any]:
    return {
        "session_id": session_id,
        "loop": int(loop_idx),
        "stage": stage,
        "started_utc": started_utc,
        "ended_utc": ended_utc,
        "ok": bool(ok),
        "rc": int(rc),
        "error": err,
        "contract_errors": contract_errors,
        "attempt_count": len(attempt_records),
        "attempts": attempt_records,
        "stage_spec_errors": stage_spec_errors,
        "failure_category": failure_category if not ok else "",
        "recoverable": bool(failure_recoverable and (not ok)),
        "failure_context": failure_context if (not ok) else {},
        "before_snapshot": before_snapshot,
        "after_snapshot": after_snapshot,
        "log": log_rel,
        "exp_verify_ok": exp_verify_ok if is_exploit_stage else None,
        "exp_verify_report": exp_verify_report if is_exploit_stage else "",
        "exp_autofix_attempts": exp_autofix_attempts if is_exploit_stage else 0,
        "exp_autofix_last_error": exp_autofix_last_error if is_exploit_stage else "",
        "stage_cache_hit": stage_cache_hit,
        "stage_cache_ref": stage_cache_ref,
        "stage_cache_saved": stage_cache_saved,
        "bundled": bool(bundled),
    }


def build_stage_result_record(
    *,
    loop_idx: int,
    stage: str,
    ok: bool,
    rc: int,
    log_rel: str,
    tx_meta_rel: str,
    failure_report_rel: str,
    decision_report_rel: str,
    mutation_manifest_rel: str,
    attempt_records: List[Dict[str, Any]],
    stage_spec_errors: List[str],
    failure_category: str,
    failure_context: Dict[str, Any],
    receipt_rel: str,
    is_exploit_stage: bool,
    exp_verify_ok: Any,
    exp_verify_report: str,
    exp_autofix_attempts: int,
    exp_autofix_last_error: str,
    stage_cache_hit: bool,
    stage_cache_ref: str,
    stage_cache_saved: str,
    bundled: bool,
    started_utc: str,
    ended_utc: str,
    stage_elapsed_sec: float,
) -> Dict[str, Any]:
    return {
        "loop": int(loop_idx),
        "stage": stage,
        "ok": bool(ok),
        "rc": int(rc),
        "log": log_rel,
        "tx_meta": tx_meta_rel,
        "failure_report": failure_report_rel,
        "decision_report": decision_report_rel,
        "mutation_manifest": mutation_manifest_rel,
        "attempts": len(attempt_records),
        "stage_spec_errors": stage_spec_errors,
        "failure_category": failure_category if not ok else "",
        "failure_context": failure_context if (not ok) else {},
        "stage_receipt": receipt_rel,
        "exp_verify_ok": exp_verify_ok if is_exploit_stage else None,
        "exp_verify_report": exp_verify_report if is_exploit_stage else "",
        "exp_autofix_attempts": exp_autofix_attempts if is_exploit_stage else 0,
        "exp_autofix_last_error": exp_autofix_last_error if is_exploit_stage else "",
        "stage_cache_hit": stage_cache_hit,
        "stage_cache_ref": stage_cache_ref,
        "stage_cache_saved": stage_cache_saved,
        "bundled": bool(bundled),
        "started_utc": started_utc,
        "ended_utc": ended_utc,
        "duration_ms": int(max(0.0, stage_elapsed_sec) * 1000.0),
        "elapsed_sec": round(float(stage_elapsed_sec), 3),
    }
